In [2]:
import random
import pandas as pd
import numpy as np

#def classify_based_on_percent(percent):

data = {"X": np.array([]), "Y": []}

for _ in range(1000):
    questions = random.randint(1, 100)  # random number of questions between 1 and 100
    correct_answers = random.randint(0, questions)  # random correct answers cannot exceed the number of questions
    ratio = correct_answers / questions * 100  # correct answers ratio as a percentage
    data["X"] = np.append(data["X"], ratio)

    if ratio <= 20:
        data["Y"].append('L1')
    elif 20 < ratio < 80:
        data["Y"].append('L2')
    else:
        data["Y"].append('L3')

df = pd.DataFrame(data)
#df['X']= df['X']100

In [3]:

df

X   Y
0    80.303030  L3
1     6.451613  L1
2    41.935484  L2
3    45.833333  L2
4    88.311688  L3
..         ...  ..
995  83.000000  L3
996   0.000000  L1
997  30.927835  L2
998  84.146341  L3
999  41.379310  L2

[1000 rows x 2 columns]

from matplotlib import pyplot as plt
df['X'].plot(kind='hist', bins=20, title='X')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('Y').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['X'].plot(kind='line', figsize=(8, 4), title='X')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['Y'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='X', y='Y', inner='box', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [4]:
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import train_test_split

from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# X contains Correct answers ratio percentages and y contains corresponding class labels
X1 = df['X'].array.reshape(-1, 1)  # we have to reshape because sklearn expects 2d array for features
y1 = df['Y']
X_train, X_test, y_train, y_test = train_test_split(X1, y1, test_size=0.2, random_state=42)
# Train the classifier
clf = RandomForestClassifier(random_state=42)
clf.fit(X1, y1)

# Let's predict class label based on percentage
class_label = clf.predict(X_test)

# Compute metrics
accuracy = accuracy_score(y_test, class_label)
precision = precision_score(y_test, class_label, average='weighted')  # use 'weighted' for multi-class problem
recall = recall_score(y_test, class_label, average='weighted')
f1 = f1_score(y_test, class_label, average='weighted')
print('Accuracy: ', accuracy)
print('Precision: ', precision)
print('Recall: ', recall)
print('F1 Score: ', f1)

print('\nClassification Report\n')
print(classification_report(y_test, class_label))

print('\nConfusion Matrix\n')
print(confusion_matrix(y_test, class_label))
print(class_label)  # it would print 'L2', 'L1' or 'L3' based on trained model



Accuracy:  1.0
Precision:  1.0
Recall:  1.0
F1 Score:  1.0

Classification Report

              precision    recall  f1-score   support

          L1       1.00      1.00      1.00        58
          L2       1.00      1.00      1.00       106
          L3       1.00      1.00      1.00        36

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200


Confusion Matrix

[[ 58   0   0]
 [  0 106   0]
 [  0   0  36]]
['L2' 'L2' 'L2' 'L2' 'L2' 'L2' 'L1' 'L3' 'L2' 'L3' 'L2' 'L1' 'L2' 'L2'
 'L2' 'L2' 'L3' 'L1' 'L2' 'L1' 'L1' 'L1' 'L2' 'L2' 'L2' 'L2' 'L1' 'L2'
 'L3' 'L2' 'L1' 'L1' 'L3' 'L3' 'L2' 'L2' 'L2' 'L1' 'L2' 'L1' 'L1' 'L2'
 'L2' 'L1' 'L2' 'L3' 'L1' 'L2' 'L2' 'L3' 'L2' 'L1' 'L1' 'L2' 'L2' 'L3'
 'L1' 'L3' 'L2' 'L2' 'L2' 'L3' 'L1' 'L2' 'L1' 'L1' 'L2' 'L2' 'L2' 'L1'
 'L2' 'L2' 'L2' 'L2' 'L2' 'L3' 'L2' 'L2' 'L2' 'L2' 'L1' 'L3' 'L2' 'L1'
 'L1' 'L1' 'L3' 'L1' 'L2' 'L3' 'L1' 'L2' 'L3'

In [5]:
inputdialoutputbackend1 = input()
# Let's predict class label for percentage
class_label0 = clf.predict([[inputdialoutputbackend1]])
print("prediction:", class_label0)
print("class label for:", inputdialoutputbackend1,"% is", class_label0)

19
prediction: ['L1']
class label for: 19 % is ['L1']


In [6]:
import joblib
# Save the model to a file
joblib.dump(clf, 'random_forest_model.pkl')


['random_forest_model.pkl']